project:
  type: website
website:
  title: "wrprates.com"
  search: 
    location: navbar
    type: overlay
  navbar:
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/wrprates/
      - icon: linkedin
        href: https://www.linkedin.com/in/wlademir-ribeiro-prates/
  google-analytics: "UA-55388899-1"
format:
  html:
    theme: litera
    css: styles.css
    toc: true
