project:
  type: website
website:
  title: "wrprates.com"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wrprates/
      - icon: linkedin
        href: https://www.linkedin.com/in/wlademir-ribeiro-prates/
format:
  html:
    theme: litera
    css: styles.css
    toc: true
