project:
  type: website

website:
  title: "wrprates.com"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: black
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



