project:
  type: website
website:
  site-url: https://wrprates.com/
  favicon: favicon.png
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: logo.png
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/wrprates/
      - icon: linkedin
        href: https://www.linkedin.com/in/wlademir-ribeiro-prates/
      - icon: youtube
        href: https://www.youtube.com/channel/UC6rS3fNDO19l0us3HEaqpAQ
  google-analytics: "G-JEQZHY19QW"
  cookie-consent: false
format:
  html:
    include-after-body: disqus.html
    theme: flatly
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
